apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-model
  labels:
    app: sentiment-model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-model
  template:
    metadata:
      labels:
        app: sentiment-model
    spec:
      containers:
      - name: sentiment-model
        image: ghcr.io/remla25-team14/model-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-token
              key: GITHUB_TOKEN
        - name: TRAINED_MODEL_VERSION
          value: "latest"  # Use latest GitHub release
        - name: MODEL_SERVICE_IMAGE_TAG
          value: "latest"
        - name: VECT_FILE_NAME
          value: "c1_BoW_Sentiment_Model.pkl"
        - name: MODEL_FILE_NAME
          value: "c2_Classifier_v1.pkl"
        - name: MODEL_CACHE_DIR
          value: "/app/model_cache"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-model
  labels:
    app: sentiment-model-serv
spec:
  selector:
    app: sentiment-model
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP