apiVersion: v1
kind: Pod
metadata:
  name: sentiment-app
  labels:
    app: sentiment-app
spec:
  containers:
  - name: sentiment-app
    image: sentiment-app:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 5001
    env:
    - name: MODEL_SERVICE_URL
      value: "http://sentiment-model:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-app-service
  labels:
    app: sentiment-app-serv
spec:
  type: NodePort
  selector:
    app: sentiment-app
  ports:
  - port: 80
    targetPort: 5001
    protocol: TCP
    name: http
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mymonitor
  labels:
    release: myprom  
spec:
  selector:
    matchLabels:
      app: sentiment-app-serv  
  endpoints:
  - interval: 1s
    path: /metrics
    port: http 